# Site settings
title: 松林的个人空间
baseurl: "https://smallsand.github.io"
#timezone: Asia/Chongqing
description: 记录生活，分享技术，提升自我

# Your information
email: 1107050213@qq.com
author: 松林
avatar: "https://avatars0.githubusercontent.com/u/12651961?s=460&v=4"
profile:   记录生活，分享技术，提升自我
#twitter_username: twitter_username
github_username:  smallSand
weibo:  kznlsl

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/

#duoshuo_shortname:  smallsand  

# get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 10
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
